version: '3.9'
services:
  db:
    image: postgres:15
    restart: on-failure
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
        - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
